language: python
python:
  - "2.7"
  - "3.6"

cache: pip

addons:
  apt:
    packages:
    - gfortran
    - python-scipy
    - python3-scipy

install:
#  - pip install -r requirements.txt
#   - pip install scipy
   - python setup.py config_fc --fcompiler=gnu95 --opt="-Ofast" --f90flags="-cpp -fopenmp -march=native" build install

script: nosetests -w tests/unit_tests

after_success:
  - coveralls