language: python
python:
  - "3.7"

cache: pip

addons:
  apt:
    packages:
    - gfortran

install:
  - pip install numpy scipy numba
  - python setup.py install

script: nosetests -w tests/unit_tests

after_success:
  - coveralls