language: python
python:
  - "3.6"

cache: pip

install:
  - pip install numpy scipy numba pyopencl pandas xarray tables astropy matplotlib tqdm seaborn emcee corner uncertainties semantic_version
  - python setup.py install

script: nosetests -w tests/unit_tests

after_success:
  - coveralls