language: python
python:
  - "2.7"

env:
  global:
    - DEPENDS="gfortran-4.9"

install:
  - python setup.by config_fc --fcompiler=gnu95 --opt="-Ofast" --f90flags="-cpp -fopenmp -march=native" build install

script: nosetests -w tests/unit_tests