language: python
python:
  - "3.6"

os:
  - linux

dist: bionic

cache: pip

install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install libpocl-dev pocl-opencl-icd; fi
  - pip install numpy scipy numba pyopencl pandas xarray tables astropy matplotlib tqdm seaborn emcee corner uncertainties semantic_version
  - python setup.py install

script: nosetests -w tests

after_success:
  - coveralls